networks:
  kafka-spark:
    name: kafka-spark
    driver: bridge

volumes:
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local

services:
  # Create a cluster with two brokers for input data.
  kafka1:
    image: docker.io/bitnami/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    volumes:
      - "kafka1_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=clusterid
    networks:
      - kafka-spark

  kafka2:
    image: docker.io/bitnami/kafka
    container_name: kafka2
    ports:
      - "9096:9096"
    volumes:
      - "kafka2_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=clusterid
    networks:
      - kafka-spark

  # kafka UI to see, how topics are distributed among the brokers.
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka_ui
    ports:
    - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
    networks:
      - kafka-spark

  producer-entertainment:
    container_name: producer-entertainment
    build:
      dockerfile: ./producers/producer-entertainment/Dockerfile
    networks:
      - kafka-spark

  producer-fuel:
    container_name: producer-fuel
    build:
      dockerfile: ./producers/producer-fuel/Dockerfile
    networks:
      - kafka-spark
